### ISSUE TITLE
Is the derivative correct in AnalyticDerivative.cpp?

### ISSUE THREAD

**Issue by TianBo-Timothy** [daviddoria/Examples#8]
In the example /Eigen/LevenbergMarquardt/AnalyticDerivative.cpp, line 14, the function f_0 is
`fvec(0) = x(0) - 5.0;  `
that isr f_0 = x - 5

I understand this as we are minimizing y = (x - 5.0)^2.

The derivative in line 21 is
`fjac(0) = 2.0f * x(0);`

However, my understanding is fjac(0) should be derivative of f_0, which results in 
`fjac(0) = 1.0f;`

I am trying to use Eigen::LevenbergMarquardt without success yet. Can you please explain what is wrong in my understanding?

**Comment by daviddoria** [comment]
You're exactly right. I just updated AnalyticDerivative.cpp and NumericalDerivative.cpp and they now produce the expected answer. Note that if you use:
fvec(0) = pow(x(0) - 5,2);
in the NumericalDerivative example you will actually also get the "right answer" (x=5), because it is actually implementing 
((x(0) - 5)^2)^2
but as you've pointed out that doesn't work in the AnalyticalDerivative case because the derivative actually doesn't match the function we're specifying.

Thanks for pointing this out!
